name: 'Setup environment'
description: 'This action will checkout code, setup node and retrieve the cache'

inputs:
  npm-token:
    description: NPM Token
    required: false

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.5

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'

    - name: Restore bun cache
      uses: actions/cache@v4
      id: bun-cache
      if: inputs.skip-install != 'true'
      with:
        path: |
          ./node_modules
          ~/.cache/Cypress
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: ${{ runner.os }}-bun-

    - name: Bun Install
      shell: bash
      if: inputs.skip-install != 'true'
      run: |
        bun install --frozen-lockfile
        bunx cypress install
