name: 'Setup environment'
description: 'This action will checkout code, setup node and retrieve the cache'

inputs:
  npm-token:
    description: NPM Token
    required: false

runs:
  using: composite
  steps:
    - name: Set Yarn version
      shell: bash
      run: yarn set version 4.6.0

    - name: Setup NodeJs 22 💿
      uses: actions/setup-node@v4
      with:
        node-version: 22
        token: ${{ inputs.npm-token }}
        registry-url: 'https://registry.npmjs.org'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore yarn cache 📦
      uses: actions/cache/restore@v4
      id: yarn-cache-restore
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install packages 🏭
      shell: bash
      run: yarn --immutable

    - name: Save yarn cache 📦
      uses: actions/cache/save@v4
      if: steps.yarn-cache-restore.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
